### ISSUE TITLE
ci: make report is failed

### ISSUE THREAD

**Issue by RevySR** [ruyisdk/riscv-gnu-toolchain-rv64ilp32#1]
https://github.com/ruyisdk/riscv-gnu-toolchain-rv64ilp32/actions/runs/7968619287/job/21753169611

**Comment by pz9115** [comment]
Fixed in https://github.com/ruyisdk/riscv-gnu-toolchain-rv64ilp32/pull/2

**Comment by RevySR** [comment]
Fixed https://github.com/ruyisdk/riscv-gnu-toolchain-rv64ilp32/commit/9a6fc8bcaeff2c1aba834b6d5d0c15dc1feddbee
