### ISSUE TITLE
undertsanding questions

### ISSUE THREAD

**Issue by yf13** [ruyisdk/riscv-gnu-toolchain-rv64ilp32#10]
Where can one find information regarding the differences between this and the mainline toolchains and usage information. For example:

- What defintions are added by this toolchain? I only know `__xlen_t` but not sure if there are any others?
- What is the right way to identify this toolchain using `#if` lines in program?
- How to build 32-bit program with this for running on 64 bit system?
- For baremetal programs, how to access addresses what live beyond 2G correctly when using this toolchain?

**Comment by pz9115** [comment]
> Where can one find information regarding the differences between this and the mainline toolchains and usage information. For example:
> 
> * What defintions are added by this toolchain? I only know  but not sure if there are any others?`__xlen_t`

This toolchain enables use `xlen 64` with `ilp32` ABI.

> * What is the right way to identify this toolchain using  lines in program?`#if`

The default configures of the toolchain is `-march=rv64gc -mabi=ilp32d`, it will auto compile program use rv64 instructions,  

> * How to build 32-bit program with this for running on 64 bit system?

The elf format is riscv 64, so it can run 32 bits program on 64 bits system.

> * For baremetal programs, how to access addresses what live beyond 2G correctly when using this toolchain?

We don't change the linker part. It will keep the same behaviour like rv64 complier, when you want to access addresses beyond 2G, an additional jump instruction will make the access correctly.

**Comment by pz9115** [comment]
> Where can one find information regarding the differences between this and the mainline toolchains and usage information. For example:
> 
> * What defintions are added by this toolchain? I only know  but not sure if there are any others?`__xlen_t`

This toolchain enables use `xlen 64` with `ilp32` ABI.

> * What is the right way to identify this toolchain using  lines in program?`#if`

The default configures of the toolchain is `-march=rv64gc -mabi=ilp32d`, it will auto compile program use rv64 instructions,  

> * How to build 32-bit program with this for running on 64 bit system?

The elf format is riscv 64, so it can run 32 bits program on 64 bits system.

> * For baremetal programs, how to access addresses what live beyond 2G correctly when using this toolchain?

We don't change the linker part. It will keep the same behavo
