### ISSUE TITLE
rv64ilp32编译器编译问题

### ISSUE THREAD

**Issue by electrocrazy** [ruyisdk/riscv-gnu-toolchain-rv64ilp32#23]
我们的芯片采用 t-head C908设计，需要在RV64上运行RV32的裸核程序。测试程序采用过之前版本的rv64ilp32工具链进行过测试。现在像采用新版的rv64ilp32工具链。在本仓库下载了源码并按照说明编译后，采用编译出来的rv64ilp32工具链编译测试代码会报如下错误。可能是什么原因呢？测试代码用之前版本的rv64ilp32编译没有问题。
问题错误信息如下：
<img width="744" alt="1、错误信息" src="https://github.com/user-attachments/assets/f46af587-af5a-4d1b-9aad-2e07d377f0e7">
<img width="698" alt="2、相关设置" src="https://github.com/user-attachments/assets/86dfc189-dd56-4884-9c07-84acc3101e48">

**Comment by guoren83** [comment]
工具链用错了！你用了 rv64lp64 的工具链，所以出现了上述错误。

**Comment by guoren83** [comment]
这个报错都被在源码里删除了的

**Comment by electrocrazy** [comment]
确实是错误使用了 rv64lp64编译器，修改为rv64ilp32编译器后OK。

**Comment by RevySR** [comment]
已澄清
