### ISSUE TITLE
如何编译出linux交叉编译链

### ISSUE THREAD

**Issue by aaaaala** [ruyisdk/riscv-gnu-toolchain-rv64ilp32#28]
平台：ubuntu 22.04
编译配置:
sudo ./configure --prefix=/opt/riscv --with-arch=rv64ga --with-abi=ilp32
sudo make linux -j $(nproc)
可以在opt中生成工具链，但使用对应的gcc编译程序会报错。

**Comment by XYenChi** [comment]
1.不需要用sudo来配置
2.--with-arch=rv64gc
3.贴一下报错信息

**Comment by aaaaala** [comment]
那个问题后面已经解决了，应该是一开始配置的问题
